# Generated by Django 6.0.1 on 2026-01-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20, unique=True)),
                ('referred_at', models.DateTimeField(auto_now_add=True)),
                ('referral_used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
