# Generated by Django 6.0.1 on 2026-01-08 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referrals', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('SIGNUP', 'SIGNUP'), ('FIRST_ORDER', 'FIRST_ORDER')], max_length=20)),
                ('reward_value', models.IntegerField()),
                ('reward_unit', models.CharField(choices=[('POINTS', 'POINTS'), ('CASH', 'CASH')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(max_length=20)),
                ('reward_value', models.IntegerField()),
                ('reward_unit', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CREDITED', 'CREDITED'), ('REVOKED', 'REVOKED')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.referral')),
            ],
        ),
    ]
